chance_value(NUM_PLAYERS, OWNED_PROPERTIES, ACTUAL_POSITION, RESULT) :-
    (OWNED_PROPERTIES >= ACTUAL_POSITION ->
        RESULT is ((NUM_PLAYERS - OWNED_PROPERTIES + ACTUAL_POSITION) mod 2)
    ;
        RESULT is ((NUM_PLAYERS + OWNED_PROPERTIES - ACTUAL_POSITION) mod 2)
    ), !.
