theme: jekyll-theme-architect
title: PPS-22-23-scalopoly
description: "Project for the course of PPS-22-23: scalopoly"
github:
  private: false
  license:
    name: MIT
  repository_url: "https://github.com/andreazammarchi3/PPS-22-scalopoly"